;;; lyzell-vc.el -*- lexical-binding; t: -*-

(setenv "SCONSFLAGS" "COMPILER=gcc DEVENV=gcc BITS=64 DEVENV_BITS=64 VERBOSE=false HOST=true MYSTIFY=0 -j12")
(setenv "NIRA_NIRATOOLS" "/home/chlyz/git/tools/NIRATools")
(setenv "NIRA_JENKINSTOOLS" "/home/chlyz/git/tools/JenkinsTools")
(setenv "BOSCH_COMPILER_X52" " ")
(setenv "CMOCK_DIR" "/home/chlyz/git/tools/NIRATools/cmock/cmock_afa2949_patched")
(setenv "COAN" "/usr/bin")
(setenv "CPPUTEST_HOME" "/home/chlyz/git/tools/NIRATools/cpputest/3.7.1")
(setenv "GCC_V850_COMPILER" "/opt/cross/")
(setenv "GCC_X86_COMPILER" " ")
(setenv "LANG" "en_US.UTF-8")
(setenv "LC_ALL" "en_US.UTF-8")
(setenv "M2RSM" "/home/chlyz/git/tools/NIRATools/MSquared/M2RSM")
(setenv "MATLAB_INCLUDES_32BIT" "/home/chlyz/git/tools/NIRATools/Matlab/includes/R2007b")
(setenv "MATLAB_INCLUDES_64BIT" "/home/chlyz/git/tools/NIRATools/Matlab/includes/R2020a")
(setenv "MW_MINGW64_LOC" " ")
(setenv "PCLint" "/home/chlyz/git/tools/NIRATools/pclint/9.00L")
(setenv "PUGIXML" "/home/chlyz/git/tools/NIRATools/Compilers/Libraries/pugixml/1.7")
(setenv "UNITY_DIR" "/home/chlyz/git/tools/NIRATools/cmock/cmock_afa2949_patched/vendor/unity")
(setenv "JAVA_HOME" "/usr/lib/jvm/java-11-openjdk-amd64")

(provide 'lyzell-terminal)
