-- Keymaps
vim.keymap.set('n', '<leader>ea', function()
    require("harpoon.mark").add_file()
end)
vim.keymap.set('n', '<leader>em', function()
    require("harpoon.ui").toggle_quick_menu()
end)
vim.keymap.set('n', '<leader>eh', function()
    require("harpoon.ui").nav_file(1)
end)
vim.keymap.set('n', '<leader>et', function()
    require("harpoon.ui").nav_file(2)
end)
vim.keymap.set('n', '<leader>en', function()
    require("harpoon.ui").nav_file(3)
end)
vim.keymap.set('n', '<leader>es', function()
    require("harpoon.ui").nav_file(4)
end)
vim.keymap.set('n', '<M-h>', function()
    require("harpoon.ui").nav_file(1)
end)
vim.keymap.set('n', '<M-t>', function()
    require("harpoon.ui").nav_file(2)
end)
vim.keymap.set('n', '<M-n>', function()
    require("harpoon.ui").nav_file(3)
end)
vim.keymap.set('n', '<M-s>', function()
    require("harpoon.ui").nav_file(4)
end)
