-- Keymaps
vim.keymap.set('n', '<leader>ta', function()
    require("harpoon.mark").add_file()
end)
vim.keymap.set('n', '<leader>tm', function()
    require("harpoon.ui").toggle_quick_menu()
end)
vim.keymap.set('n', '<leader>tn', function()
    require("harpoon.ui").nav_file(1)
end)
vim.keymap.set('n', '<leader>te', function()
    require("harpoon.ui").nav_file(2)
end)
vim.keymap.set('n', '<leader>ti', function()
    require("harpoon.ui").nav_file(3)
end)
vim.keymap.set('n', '<leader>to', function()
    require("harpoon.ui").nav_file(4)
end)
