require("lyzell.options")
require("lyzell.plugins")
require("lyzell.keymaps")
require("lyzell.comment")
require("lyzell.completion")
require("lyzell.harpoon")
require("lyzell.telescope")
-- require("lyzell.lualine")
