vim.g.mapleader = " "

vim.keymap.set('n', '<leader><leader>', '<C-6>')
vim.keymap.set('i', '<C-h>', '<C-w>')
vim.keymap.set('c', '<C-h>', '<C-w>')

-- Copy and pasting from the system clipboard.
vim.keymap.set('n', '<leader>p', 'mz"+p`z')
vim.keymap.set('n', '<leader>=p', 'mz"+pv`]==0`z')
vim.keymap.set('n', '<leader>y', '"+y')
vim.keymap.set('v', '<leader>y', '"+y')

vim.keymap.set('n', '<leader>w', function () vim.cmd("write") end)
vim.keymap.set('n', '<leader>x', function () vim.cmd("xit") end)
vim.keymap.set('n', '<leader>q', function () vim.cmd("quit") end)
vim.keymap.set('n', '<leader>k', function () vim.cmd("bdelete") end)

vim.keymap.set('n', '<leader>ck', function ()
    vim.cmd("edit /home/chlyz/.config/kitty/kitty.conf")
end)

vim.keymap.set('n', '<leader>cv', function ()
    vim.cmd("edit /home/chlyz/.config/nvim/init.lua")
end)

vim.keymap.set('n', '<leader>cs', function ()
    vim.cmd("source /home/chlyz/.config/nvim/init.lua")
end)

-- Git
vim.keymap.set('n', '<leader>gs', function ()
    vim.cmd("G")
end)

-- Telescope
vim.keymap.set('n', '<leader>>', function ()
    require('telescope.builtin').find_files()
end)
vim.keymap.set('n', '<leader>.', function ()
    require('telescope.builtin').git_files()
end)
vim.keymap.set('n', '<leader>,', function ()
    require('telescope.builtin').buffers()
end)
vim.keymap.set('n', '<leader>;', function ()
    require('telescope.builtin').current_buffer_tags()
end)
vim.keymap.set('n', '<leader>:', function ()
    require('telescope.builtin').command_history()
end)

-- Harpoon
vim.keymap.set('n', '<leader>ea', function()
    require("harpoon.mark").add_file()
end)
vim.keymap.set('n', '<leader>em', function()
    require("harpoon.ui").toggle_quick_menu()
end)
vim.keymap.set('n', '<leader>eh', function()
    require("harpoon.ui").nav_file(1)
end)
vim.keymap.set('n', '<leader>et', function()
    require("harpoon.ui").nav_file(2)
end)
vim.keymap.set('n', '<leader>en', function()
    require("harpoon.ui").nav_file(3)
end)
vim.keymap.set('n', '<leader>es', function()
    require("harpoon.ui").nav_file(4)
end)
vim.keymap.set('n', '<M-h>', function()
    require("harpoon.ui").nav_file(1)
end)
vim.keymap.set('n', '<M-t>', function()
    require("harpoon.ui").nav_file(2)
end)
vim.keymap.set('n', '<M-n>', function()
    require("harpoon.ui").nav_file(3)
end)
vim.keymap.set('n', '<M-s>', function()
    require("harpoon.ui").nav_file(4)
end)
